"""
SAARTHI — Agent Communication Models
Pydantic schemas for action requests generated by external agents.
"""
from pydantic import BaseModel, Field
from typing import Dict, Any, Optional

class ActionRequest(BaseModel):
    scenario_id: str
    workflow_id: Optional[str] = None
    agent_id: str = "demo-agent-01"
    customer: str
    order_id: str
    action: str = "customer_refund"
    amount: float = 0.0
    agent_claim: Dict[str, Any] = Field(default_factory=dict)
    trusted_state: Dict[str, Any] = Field(default_factory=dict)
    context: Dict[str, Any] = Field(default_factory=dict)

class ActionEvaluationResponse(BaseModel):
    workflow_id: str
    decision: str
    reason: str
    reasons: list = Field(default_factory=list)
    verification: Dict[str, Any] = Field(default_factory=dict)
    policy: Dict[str, Any] = Field(default_factory=dict)
    ml_anomaly: Dict[str, Any] = Field(default_factory=dict)
    risk: Dict[str, Any] = Field(default_factory=dict)
    status: str
    review_id: Optional[str] = None
